services:
  cigniter-docker:
    container_name: nama-container
    build: .
    volumes:
      - ./container-app:/var/www/html
    ports:
      - 8080:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: userpassword
      MYSQL_DATABASE: dbname
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
